services:
  app:
    ports:
      - "8081:8081"
    volumes:
      - ./seed.sql:/seed/seed.sql:ro
    environment:
      Jwt__Secret: "local-development-secret-change-before-production-2026"
      ASPNETCORE_ENVIRONMENT: Development
      Seed__Path: /seed/seed.sql
  db:
    ports:
      - "5433:5432"
